use std::fmt;

/// Stable identifier assigned by the host for a runtime plugin/node instance.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PluginId(pub String);

impl PluginId {
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }
}

impl fmt::Display for PluginId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Values that can be sent through the host-mediated plugin control channel.
#[derive(Debug, Clone, PartialEq)]
pub enum ParameterValue {
    Bool(bool),
    I64(i64),
    F64(f64),
    Text(String),
}

/// Public description of a controllable plugin parameter.
#[derive(Debug, Clone, PartialEq)]
pub struct ParameterInfo {
    pub id: String,
    pub name: String,
    pub value: ParameterValue,
    pub min: Option<ParameterValue>,
    pub max: Option<ParameterValue>,
}

/// Commands generated by host automation rules or UI controls.
#[derive(Debug, Clone, PartialEq)]
pub enum PluginCommand {
    SetParameter {
        plugin_id: PluginId,
        parameter_id: String,
        value: ParameterValue,
        effective_frame: Option<u64>,
    },
}

/// Capability implemented by plugins whose parameters can be controlled by the host.
pub trait ControllablePlugin: Send {
    fn plugin_id(&self) -> PluginId;
    fn parameters(&self) -> Vec<ParameterInfo>;
    fn set_parameter(&mut self, id: &str, value: ParameterValue) -> crate::Result<()>;
    fn get_parameter(&self, id: &str) -> Option<ParameterValue>;
}
